### ISSUE TITLE
Tileset "fonts" not found

### ISSUE THREAD

**Issue by mosinuga** [t-rex-tileserver/t-rex#174] opened 2019-11-18 21:52 UTC
Hello,

We are running t-rex inside docker and it is reporting some errors (I think it's with maputnik, as it is when maputnik is invoked that the error gets reported):

`thread 'actix-rt:worker:1' panicked at 'Tileset 'fonts' not found', src/libcore/option.rs:1036:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Panic in Arbiter thread, shutting down system.
2019-11-18 17:33:49.043 ERROR Worker has died 1, restarting
thread 'actix-rt:worker:0' panicked at 'Tileset 'fonts' not found', src/libcore/option.rs:1036:5
Panic in Arbiter thread, shutting down system.
2019-11-18 17:37:59.549 ERROR Worker has died 0, restarting
thread 'actix-rt:worker:3' panicked at 'Tileset 'fonts' not found', src/libcore/option.rs:1036:5
Panic in Arbiter thread, shutting down system.
2019-11-18 17:53:00.137 ERROR Worker has died 2, restarting
thread 'actix-rt:worker:4' panicked at 'Tileset 'fonts' not found', src/libcore/option.rs:1036:5
Panic in Arbiter thread, shutting down system.
2019-11-18 21:38:57.034 ERROR Worker has died 2, restarting
thread 'actix-rt:worker:2' panicked at 'Tileset 'fonts' not found', src/libcore/option.rs:1036:5
Panic in Arbiter thread, shutting down system.
2019-11-18 21:43:54.861 ERROR Worker has died 1, restarting
thread 'actix-rt:worker:6' panicked at 'Tileset 'fonts' not found', src/libcore/option.rs:1036:5
Panic in Arbiter thread, shutting down system.`

**Comment by pka** [comment] 2019-11-28 17:26
Closing this as duplicate of #159

**Closed by pka** 2019-11-28 17:26 UTC
