### ISSUE TITLE
Should invalid geometry in the result from a feature query be fixed?

### ISSUE THREAD

**Issue by chau-intl** [t-rex-tileserver/t-rex#206] opened 2020-08-26 06:35 UTC
When configuring `t-rex` to use simplify on a PostGIS _polygon_ source simplification seems to be done using the PostGIS function `ST_SnapToGrid()`. The result from that operation contains some visual artefacts and occasionally also invalid geometry. See the following image (artefacts circled in red):

![image](https://user-images.githubusercontent.com/6311686/91166417-a2f97700-e6d2-11ea-9151-cae4971328c9.png)

While these artefacts normally should be too small to be visible I wonder if invalid geometry might cause issues later when rendering on the client? Issues could be either performance or visual errors due to interpretation of the invalid geometry.

I haven't browsed the code other than the [SQL ](https://github.com/t-rex-tileserver/t-rex/blob/2be4a6edc690f28e675124504470bfc3fb3becba/t-rex-core/src/datasource/postgis_ds.rs#L282) creation when using simplification and thus I don't know if any geometry fixing is performed at a later stage (though looking at the returned `pbf` files I do see invalid geometry).

If no geometry fixing is done at a later stage would it then make sense to wrap the entire SQL request in a `ST_MakeValid(...)` call and afterwards remove anything not polygon (for polygons) and anything not line (for lines)? 
Currently the `make_valid: true` configuration parameter only applies the `ST_MakeValid(...)` directly on the source geometry before clipping and simplification.

**Comment by pka** [comment] 2020-08-26 08:32
Hi Casper, Thanks for the detailed problem description!
According to the Mapbox spec, valid geometries are required by the client. For performance reasons we don't apply `ST_MakeValid` automatically, but you can activate it by adding `make_valid=true` to the layer [configuration](https://t-rex.tileserver.ch/doc/reference/#tileset).

**Comment by chau-intl** [comment] 2020-08-26 08:51
Hi Pirmin, 

As I wrote in the original issue report I don't think the `make_valid = true` makes the resulting geometry in the tiles valid, it only makes the geometry from the PostGIS source valid BEFORE any clipping and simplifications are made. This is an example which I manually prettified from the `t-rex` log:

```
SELECT COALESCE(
	ST_SnapToGrid(
		ST_Multi(
			ST_Buffer(
				ST_Intersection(
					ST_MakeValid(geometri),
					ST_Buffer(
						ST_MakeEnvelope($1,$2,$3,$4,25832),
						1$5::FLOAT8
					)
				),
				0.0
			)
		), 
		$5::FLOAT8/2
	),
	ST_GeomFromText('MULTIPOLYGON EMPTY',25832)
)::geometry(MULTIPOLYGON,25832) AS geometri,
"objectid",
"shape_length",
"shape_area" FROM (
	SELECT * FROM MYTABLE 
	WHERE geometri && 
	ST_Buffer(
		ST_MakeEnvelope($1,$2,$3,$4,25832),
		1$5::FLOAT8
	)
) AS _q
```
It looks like the `ST_MakeValid(...)` is only performed on the input geometry and NOT on the resulting geometry in the vector tile. 

I think that `ST_SnapToGrid` can cause _self intersections_ when snapping and thus collapsing geometry, but I don't know if `ST_SimplifyPreserveTopology` can return invalid geometry? If only the `ST_SnapToGrid` can cause invalid geometry I guess it requires a `ST_MakeValid` call to the result - no matter what the configuration specifies. But a middle path would be to only apply it IF the `make_valid = true` is specified.

Does that make sense?

**Comment by pka** [comment] 2020-08-26 09:46
You are right, `ST_MakeValid` is applied before `ST_SnapToGrid`. I think we could always apply it after `ST_SnapToGrid` to guarantee valid simplified geometries. Will investage whether `ST_SimplifyPreserveTopology` already guarantees valid geometries.

**Comment by chau-intl** [comment] 2020-08-26 11:16
Great to hear that. I have found a new example where both spikes and invalid geometry happens:
![image](https://user-images.githubusercontent.com/6311686/91296921-ad347780-e79d-11ea-8211-6db2dcaef404.png)
I'm not exactly sure about the parameters but I think the zoom level was around 8 and the simplification is probably default. 

I have [attached](https://github.com/t-rex-tileserver/t-rex/files/5129411/data.zip) the data as GeoPackage with the original polygon and the polygon from the vector tile.

Let me know if I should try to dig up more information.

**Comment by pka** [comment] 2020-09-02 21:36
`ST_MakeValid` is now applied to the result of `ST_SnapToGrid`

**Comment by chau-intl** [comment] 2020-09-04 05:48
I made a simple test with an extract of the changed code using the polygon above and the value `20` (_just a pseudo-random number_) as tolerance

`SELECT COALESCE(ST_MakeValid(ST_SnapToGrid(ST_GeomFromText('VERY_LONG_WKT_FROM_DATA.GPKG/ORIGINAL', 25832),
20)),ST_GeomFromText('MULTIPOLYGON EMPTY',25832))::geometry(MULTIPOLYGON,25832)`

and I get this error:

`SQL Error [22023]: ERROR: Geometry type (GeometryCollection) does not match column type (MultiPolygon)`

The reason is that any collapsed polygons will turn into `LINESTRING`'s and along with the remaining polygons will result in a `GEOMETRYCOLLECTION`.

I think the left overs from `ST_MakeValid(...)` 

`MultiLineString ((601140 6130520, 601140 6130540),(601300 6130400, 601280 6130400),(601600 6130920, 601600 6130940),(600340 6130720, 600320 6130720),(600120 6130800, 600140 6130800),(600100 6130780, 600080 6130780),(600020 6130680, 600020 6130700),(600480 6130220, 600460 6130220),(600420 6130040, 600400 6130040),(600400 6130100, 600420 6130100),(600180 6130100, 600160 6130100),(600560 6130040, 600560 6130020),(601060 6129880, 601040 6129880),(601000 6129980, 600980 6129980))`

needs to be removed before proceeding. I don't know if `ST_MakeValid` can collapse polygons into points also?

**Comment by pka** [comment] 2020-09-08 07:57
Does the licence allow using your GPKG in the t-rex test suite?

**Comment by chau-intl** [comment] 2020-09-08 11:29
Yes, and if attribution is possible then please use something like: 

_"Contains data from The Danish Agency for Data Supply and Efficiency, Danske stednavne, 2020"_.

**Comment by pka** [comment] 2020-12-06 22:43
I've merged your fix using `ST_CollectionExtract` and `ST_Buffer` in  in 248dfc5 and f9548e0. Thanks a lot!

**Closed by pka** 2020-12-06 22:43 UTC
Labels: bug

**Comment by tobwen** [comment] 2021-09-17 23:53
The use of ST_Buffer(0) is *REALLY* not recommended. Once bows are in a polygon, a portion of that polygon is randomly discarded. You can't say which portion of a polygon gets eliminated. This can have unexpected effects.

Next PostGIS will come with a brand new `ST_MakeValid`: https://blog.crunchydata.com/blog/waiting-for-postgis-3.2-st_makevalid

**Comment by tobwen** [comment] 2021-09-30 21:41
You're using `ST_SnapToGrid()` - this produces bad polygons by design. Maybe you should try `ST_ReducePrecision()`. It produces valid polygons. 

```SELECT ST_ReducePrecision(geom, 32) AS geom FROM original;```
![image](https://user-images.githubusercontent.com/1864057/135533995-36b36d90-de60-4d8f-a645-ec23659e272b.png)

```SELECT ST_ReducePrecision(geom, 64) AS geom FROM original;```
![image](https://user-images.githubusercontent.com/1864057/135534013-f2fcdd05-d0ff-4136-8525-1681477d4398.png)

**Comment by pka** [comment] 2021-09-30 22:07
Looks promsing, missed that new function in 3.1! But I would only add it after a PostGIS version detection, because PostGIS 3.1 is not that common yet.

**Comment by tobwen** [comment] 2021-09-30 22:17
True, but it additionally needs _GEOS 3.9+_. _PostGIS 3.2_ is going to be released soon. GEOS made a huge quality jump in validating geometries.

**Comment by tobwen** [comment] 2021-09-30 22:30
I think I'll create a fork of this and test it in Docker (performance, etc.)
